// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.powertac.server.module.databaseservice.domain;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.powertac.server.module.databaseservice.domain.BrokerCompetitionDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect BrokerCompetitionIntegrationTest_Roo_IntegrationTest {
    
    declare @type: BrokerCompetitionIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: BrokerCompetitionIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: BrokerCompetitionIntegrationTest: @Transactional;
    
    @Autowired
    private BrokerCompetitionDataOnDemand BrokerCompetitionIntegrationTest.dod;
    
    @Test
    public void BrokerCompetitionIntegrationTest.testCountBrokerCompetitions() {
        org.junit.Assert.assertNotNull("Data on demand for 'BrokerCompetition' failed to initialize correctly", dod.getRandomBrokerCompetition());
        long count = org.powertac.server.module.databaseservice.domain.BrokerCompetition.countBrokerCompetitions();
        org.junit.Assert.assertTrue("Counter for 'BrokerCompetition' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void BrokerCompetitionIntegrationTest.testFindBrokerCompetition() {
        org.powertac.server.module.databaseservice.domain.BrokerCompetition obj = dod.getRandomBrokerCompetition();
        org.junit.Assert.assertNotNull("Data on demand for 'BrokerCompetition' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'BrokerCompetition' failed to provide an identifier", id);
        obj = org.powertac.server.module.databaseservice.domain.BrokerCompetition.findBrokerCompetition(id);
        org.junit.Assert.assertNotNull("Find method for 'BrokerCompetition' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'BrokerCompetition' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void BrokerCompetitionIntegrationTest.testFindAllBrokerCompetitions() {
        org.junit.Assert.assertNotNull("Data on demand for 'BrokerCompetition' failed to initialize correctly", dod.getRandomBrokerCompetition());
        long count = org.powertac.server.module.databaseservice.domain.BrokerCompetition.countBrokerCompetitions();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'BrokerCompetition', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<org.powertac.server.module.databaseservice.domain.BrokerCompetition> result = org.powertac.server.module.databaseservice.domain.BrokerCompetition.findAllBrokerCompetitions();
        org.junit.Assert.assertNotNull("Find all method for 'BrokerCompetition' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'BrokerCompetition' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void BrokerCompetitionIntegrationTest.testFindBrokerCompetitionEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'BrokerCompetition' failed to initialize correctly", dod.getRandomBrokerCompetition());
        long count = org.powertac.server.module.databaseservice.domain.BrokerCompetition.countBrokerCompetitions();
        if (count > 20) count = 20;
        java.util.List<org.powertac.server.module.databaseservice.domain.BrokerCompetition> result = org.powertac.server.module.databaseservice.domain.BrokerCompetition.findBrokerCompetitionEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'BrokerCompetition' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'BrokerCompetition' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void BrokerCompetitionIntegrationTest.testFlush() {
        org.powertac.server.module.databaseservice.domain.BrokerCompetition obj = dod.getRandomBrokerCompetition();
        org.junit.Assert.assertNotNull("Data on demand for 'BrokerCompetition' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'BrokerCompetition' failed to provide an identifier", id);
        obj = org.powertac.server.module.databaseservice.domain.BrokerCompetition.findBrokerCompetition(id);
        org.junit.Assert.assertNotNull("Find method for 'BrokerCompetition' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyBrokerCompetition(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'BrokerCompetition' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void BrokerCompetitionIntegrationTest.testMerge() {
        org.powertac.server.module.databaseservice.domain.BrokerCompetition obj = dod.getRandomBrokerCompetition();
        org.junit.Assert.assertNotNull("Data on demand for 'BrokerCompetition' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'BrokerCompetition' failed to provide an identifier", id);
        obj = org.powertac.server.module.databaseservice.domain.BrokerCompetition.findBrokerCompetition(id);
        boolean modified =  dod.modifyBrokerCompetition(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        org.powertac.server.module.databaseservice.domain.BrokerCompetition merged = (org.powertac.server.module.databaseservice.domain.BrokerCompetition) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'BrokerCompetition' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void BrokerCompetitionIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'BrokerCompetition' failed to initialize correctly", dod.getRandomBrokerCompetition());
        org.powertac.server.module.databaseservice.domain.BrokerCompetition obj = dod.getNewTransientBrokerCompetition(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'BrokerCompetition' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'BrokerCompetition' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'BrokerCompetition' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void BrokerCompetitionIntegrationTest.testRemove() {
        org.powertac.server.module.databaseservice.domain.BrokerCompetition obj = dod.getRandomBrokerCompetition();
        org.junit.Assert.assertNotNull("Data on demand for 'BrokerCompetition' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'BrokerCompetition' failed to provide an identifier", id);
        obj = org.powertac.server.module.databaseservice.domain.BrokerCompetition.findBrokerCompetition(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'BrokerCompetition' with identifier '" + id + "'", org.powertac.server.module.databaseservice.domain.BrokerCompetition.findBrokerCompetition(id));
    }
    
}
