// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.powertac.server.module.databaseservice.domain;

import java.util.List;
import java.util.Random;
import org.powertac.server.module.databaseservice.domain.BrokerCompetition;
import org.springframework.stereotype.Component;

privileged aspect BrokerCompetitionDataOnDemand_Roo_DataOnDemand {
    
    declare @type: BrokerCompetitionDataOnDemand: @Component;
    
    private Random BrokerCompetitionDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<BrokerCompetition> BrokerCompetitionDataOnDemand.data;
    
    public BrokerCompetition BrokerCompetitionDataOnDemand.getNewTransientBrokerCompetition(int index) {
        org.powertac.server.module.databaseservice.domain.BrokerCompetition obj = new org.powertac.server.module.databaseservice.domain.BrokerCompetition();
        obj.setBroker(null);
        obj.setCompetition(null);
        obj.setReady(Boolean.TRUE);
        return obj;
    }
    
    public BrokerCompetition BrokerCompetitionDataOnDemand.getSpecificBrokerCompetition(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        BrokerCompetition obj = data.get(index);
        return BrokerCompetition.findBrokerCompetition(obj.getId());
    }
    
    public BrokerCompetition BrokerCompetitionDataOnDemand.getRandomBrokerCompetition() {
        init();
        BrokerCompetition obj = data.get(rnd.nextInt(data.size()));
        return BrokerCompetition.findBrokerCompetition(obj.getId());
    }
    
    public boolean BrokerCompetitionDataOnDemand.modifyBrokerCompetition(BrokerCompetition obj) {
        return false;
    }
    
    public void BrokerCompetitionDataOnDemand.init() {
        data = org.powertac.server.module.databaseservice.domain.BrokerCompetition.findBrokerCompetitionEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'BrokerCompetition' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<org.powertac.server.module.databaseservice.domain.BrokerCompetition>();
        for (int i = 0; i < 10; i++) {
            org.powertac.server.module.databaseservice.domain.BrokerCompetition obj = getNewTransientBrokerCompetition(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
