// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.powertac.server.module.databaseservice.domain;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.powertac.server.module.databaseservice.domain.CashRecordDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect CashRecordIntegrationTest_Roo_IntegrationTest {
    
    declare @type: CashRecordIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: CashRecordIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: CashRecordIntegrationTest: @Transactional;
    
    @Autowired
    private CashRecordDataOnDemand CashRecordIntegrationTest.dod;
    
    @Test
    public void CashRecordIntegrationTest.testCountCashRecords() {
        org.junit.Assert.assertNotNull("Data on demand for 'CashRecord' failed to initialize correctly", dod.getRandomCashRecord());
        long count = org.powertac.server.module.databaseservice.domain.CashRecord.countCashRecords();
        org.junit.Assert.assertTrue("Counter for 'CashRecord' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void CashRecordIntegrationTest.testFindCashRecord() {
        org.powertac.server.module.databaseservice.domain.CashRecord obj = dod.getRandomCashRecord();
        org.junit.Assert.assertNotNull("Data on demand for 'CashRecord' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'CashRecord' failed to provide an identifier", id);
        obj = org.powertac.server.module.databaseservice.domain.CashRecord.findCashRecord(id);
        org.junit.Assert.assertNotNull("Find method for 'CashRecord' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'CashRecord' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void CashRecordIntegrationTest.testFindAllCashRecords() {
        org.junit.Assert.assertNotNull("Data on demand for 'CashRecord' failed to initialize correctly", dod.getRandomCashRecord());
        long count = org.powertac.server.module.databaseservice.domain.CashRecord.countCashRecords();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'CashRecord', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<org.powertac.server.module.databaseservice.domain.CashRecord> result = org.powertac.server.module.databaseservice.domain.CashRecord.findAllCashRecords();
        org.junit.Assert.assertNotNull("Find all method for 'CashRecord' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'CashRecord' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void CashRecordIntegrationTest.testFindCashRecordEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'CashRecord' failed to initialize correctly", dod.getRandomCashRecord());
        long count = org.powertac.server.module.databaseservice.domain.CashRecord.countCashRecords();
        if (count > 20) count = 20;
        java.util.List<org.powertac.server.module.databaseservice.domain.CashRecord> result = org.powertac.server.module.databaseservice.domain.CashRecord.findCashRecordEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'CashRecord' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'CashRecord' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void CashRecordIntegrationTest.testFlush() {
        org.powertac.server.module.databaseservice.domain.CashRecord obj = dod.getRandomCashRecord();
        org.junit.Assert.assertNotNull("Data on demand for 'CashRecord' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'CashRecord' failed to provide an identifier", id);
        obj = org.powertac.server.module.databaseservice.domain.CashRecord.findCashRecord(id);
        org.junit.Assert.assertNotNull("Find method for 'CashRecord' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyCashRecord(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'CashRecord' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CashRecordIntegrationTest.testMerge() {
        org.powertac.server.module.databaseservice.domain.CashRecord obj = dod.getRandomCashRecord();
        org.junit.Assert.assertNotNull("Data on demand for 'CashRecord' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'CashRecord' failed to provide an identifier", id);
        obj = org.powertac.server.module.databaseservice.domain.CashRecord.findCashRecord(id);
        boolean modified =  dod.modifyCashRecord(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        org.powertac.server.module.databaseservice.domain.CashRecord merged = (org.powertac.server.module.databaseservice.domain.CashRecord) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'CashRecord' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CashRecordIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'CashRecord' failed to initialize correctly", dod.getRandomCashRecord());
        org.powertac.server.module.databaseservice.domain.CashRecord obj = dod.getNewTransientCashRecord(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'CashRecord' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'CashRecord' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'CashRecord' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void CashRecordIntegrationTest.testRemove() {
        org.powertac.server.module.databaseservice.domain.CashRecord obj = dod.getRandomCashRecord();
        org.junit.Assert.assertNotNull("Data on demand for 'CashRecord' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'CashRecord' failed to provide an identifier", id);
        obj = org.powertac.server.module.databaseservice.domain.CashRecord.findCashRecord(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'CashRecord' with identifier '" + id + "'", org.powertac.server.module.databaseservice.domain.CashRecord.findCashRecord(id));
    }
    
}
