// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.powertac.server.module.databaseservice.domain;

import java.util.List;
import java.util.Random;
import org.powertac.server.module.databaseservice.domain.Competition;
import org.springframework.stereotype.Component;

privileged aspect CompetitionDataOnDemand_Roo_DataOnDemand {
    
    declare @type: CompetitionDataOnDemand: @Component;
    
    private Random CompetitionDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<Competition> CompetitionDataOnDemand.data;
    
    public Competition CompetitionDataOnDemand.getNewTransientCompetition(int index) {
        org.powertac.server.module.databaseservice.domain.Competition obj = new org.powertac.server.module.databaseservice.domain.Competition();
        obj.setCompetitionStatus(null);
        obj.setCurrentCompetition(Boolean.TRUE);
        obj.setDateCreated(null);
        obj.setEnabled(Boolean.TRUE);
        obj.setLastUpdated(null);
        obj.setName("name_" + index);
        return obj;
    }
    
    public Competition CompetitionDataOnDemand.getSpecificCompetition(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Competition obj = data.get(index);
        return Competition.findCompetition(obj.getId());
    }
    
    public Competition CompetitionDataOnDemand.getRandomCompetition() {
        init();
        Competition obj = data.get(rnd.nextInt(data.size()));
        return Competition.findCompetition(obj.getId());
    }
    
    public boolean CompetitionDataOnDemand.modifyCompetition(Competition obj) {
        return false;
    }
    
    public void CompetitionDataOnDemand.init() {
        data = org.powertac.server.module.databaseservice.domain.Competition.findCompetitionEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Competition' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<org.powertac.server.module.databaseservice.domain.Competition>();
        for (int i = 0; i < 10; i++) {
            org.powertac.server.module.databaseservice.domain.Competition obj = getNewTransientCompetition(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
