// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.powertac.server.module.databaseservice.domain;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.powertac.server.module.databaseservice.domain.CompetitionDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect CompetitionIntegrationTest_Roo_IntegrationTest {
    
    declare @type: CompetitionIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: CompetitionIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: CompetitionIntegrationTest: @Transactional;
    
    @Autowired
    private CompetitionDataOnDemand CompetitionIntegrationTest.dod;
    
    @Test
    public void CompetitionIntegrationTest.testCountCompetitions() {
        org.junit.Assert.assertNotNull("Data on demand for 'Competition' failed to initialize correctly", dod.getRandomCompetition());
        long count = org.powertac.server.module.databaseservice.domain.Competition.countCompetitions();
        org.junit.Assert.assertTrue("Counter for 'Competition' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void CompetitionIntegrationTest.testFindCompetition() {
        org.powertac.server.module.databaseservice.domain.Competition obj = dod.getRandomCompetition();
        org.junit.Assert.assertNotNull("Data on demand for 'Competition' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Competition' failed to provide an identifier", id);
        obj = org.powertac.server.module.databaseservice.domain.Competition.findCompetition(id);
        org.junit.Assert.assertNotNull("Find method for 'Competition' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Competition' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void CompetitionIntegrationTest.testFindAllCompetitions() {
        org.junit.Assert.assertNotNull("Data on demand for 'Competition' failed to initialize correctly", dod.getRandomCompetition());
        long count = org.powertac.server.module.databaseservice.domain.Competition.countCompetitions();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Competition', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<org.powertac.server.module.databaseservice.domain.Competition> result = org.powertac.server.module.databaseservice.domain.Competition.findAllCompetitions();
        org.junit.Assert.assertNotNull("Find all method for 'Competition' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Competition' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void CompetitionIntegrationTest.testFindCompetitionEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Competition' failed to initialize correctly", dod.getRandomCompetition());
        long count = org.powertac.server.module.databaseservice.domain.Competition.countCompetitions();
        if (count > 20) count = 20;
        java.util.List<org.powertac.server.module.databaseservice.domain.Competition> result = org.powertac.server.module.databaseservice.domain.Competition.findCompetitionEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Competition' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Competition' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void CompetitionIntegrationTest.testFlush() {
        org.powertac.server.module.databaseservice.domain.Competition obj = dod.getRandomCompetition();
        org.junit.Assert.assertNotNull("Data on demand for 'Competition' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Competition' failed to provide an identifier", id);
        obj = org.powertac.server.module.databaseservice.domain.Competition.findCompetition(id);
        org.junit.Assert.assertNotNull("Find method for 'Competition' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyCompetition(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Competition' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CompetitionIntegrationTest.testMerge() {
        org.powertac.server.module.databaseservice.domain.Competition obj = dod.getRandomCompetition();
        org.junit.Assert.assertNotNull("Data on demand for 'Competition' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Competition' failed to provide an identifier", id);
        obj = org.powertac.server.module.databaseservice.domain.Competition.findCompetition(id);
        boolean modified =  dod.modifyCompetition(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        org.powertac.server.module.databaseservice.domain.Competition merged = (org.powertac.server.module.databaseservice.domain.Competition) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Competition' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CompetitionIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Competition' failed to initialize correctly", dod.getRandomCompetition());
        org.powertac.server.module.databaseservice.domain.Competition obj = dod.getNewTransientCompetition(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Competition' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Competition' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Competition' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void CompetitionIntegrationTest.testRemove() {
        org.powertac.server.module.databaseservice.domain.Competition obj = dod.getRandomCompetition();
        org.junit.Assert.assertNotNull("Data on demand for 'Competition' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Competition' failed to provide an identifier", id);
        obj = org.powertac.server.module.databaseservice.domain.Competition.findCompetition(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Competition' with identifier '" + id + "'", org.powertac.server.module.databaseservice.domain.Competition.findCompetition(id));
    }
    
}
