// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.powertac.server.module.databaseservice.domain;

import java.util.List;
import java.util.Random;
import org.powertac.server.module.databaseservice.domain.Customer;
import org.springframework.stereotype.Component;

privileged aspect CustomerDataOnDemand_Roo_DataOnDemand {
    
    declare @type: CustomerDataOnDemand: @Component;
    
    private Random CustomerDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<Customer> CustomerDataOnDemand.data;
    
    public Customer CustomerDataOnDemand.getNewTransientCustomer(int index) {
        org.powertac.server.module.databaseservice.domain.Customer obj = new org.powertac.server.module.databaseservice.domain.Customer();
        return obj;
    }
    
    public Customer CustomerDataOnDemand.getSpecificCustomer(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Customer obj = data.get(index);
        return Customer.findCustomer(obj.getId());
    }
    
    public Customer CustomerDataOnDemand.getRandomCustomer() {
        init();
        Customer obj = data.get(rnd.nextInt(data.size()));
        return Customer.findCustomer(obj.getId());
    }
    
    public boolean CustomerDataOnDemand.modifyCustomer(Customer obj) {
        return false;
    }
    
    public void CustomerDataOnDemand.init() {
        data = org.powertac.server.module.databaseservice.domain.Customer.findCustomerEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Customer' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<org.powertac.server.module.databaseservice.domain.Customer>();
        for (int i = 0; i < 10; i++) {
            org.powertac.server.module.databaseservice.domain.Customer obj = getNewTransientCustomer(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
