// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.powertac.server.module.databaseservice.domain;

import java.util.List;
import java.util.Random;
import org.powertac.server.module.databaseservice.domain.MeterReading;
import org.springframework.stereotype.Component;

privileged aspect MeterReadingDataOnDemand_Roo_DataOnDemand {
    
    declare @type: MeterReadingDataOnDemand: @Component;
    
    private Random MeterReadingDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<MeterReading> MeterReadingDataOnDemand.data;
    
    public MeterReading MeterReadingDataOnDemand.getNewTransientMeterReading(int index) {
        org.powertac.server.module.databaseservice.domain.MeterReading obj = new org.powertac.server.module.databaseservice.domain.MeterReading();
        obj.setAmount(new java.math.BigDecimal(index));
        obj.setCompetition(null);
        obj.setCustomer(null);
        obj.setTimeslot(null);
        return obj;
    }
    
    public MeterReading MeterReadingDataOnDemand.getSpecificMeterReading(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        MeterReading obj = data.get(index);
        return MeterReading.findMeterReading(obj.getId());
    }
    
    public MeterReading MeterReadingDataOnDemand.getRandomMeterReading() {
        init();
        MeterReading obj = data.get(rnd.nextInt(data.size()));
        return MeterReading.findMeterReading(obj.getId());
    }
    
    public boolean MeterReadingDataOnDemand.modifyMeterReading(MeterReading obj) {
        return false;
    }
    
    public void MeterReadingDataOnDemand.init() {
        data = org.powertac.server.module.databaseservice.domain.MeterReading.findMeterReadingEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'MeterReading' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<org.powertac.server.module.databaseservice.domain.MeterReading>();
        for (int i = 0; i < 10; i++) {
            org.powertac.server.module.databaseservice.domain.MeterReading obj = getNewTransientMeterReading(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
