// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.powertac.server.module.databaseservice.domain;

import java.util.List;
import java.util.Random;
import org.powertac.server.module.databaseservice.domain.Product;
import org.springframework.stereotype.Component;

privileged aspect ProductDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ProductDataOnDemand: @Component;
    
    private Random ProductDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<Product> ProductDataOnDemand.data;
    
    public Product ProductDataOnDemand.getNewTransientProduct(int index) {
        org.powertac.server.module.databaseservice.domain.Product obj = new org.powertac.server.module.databaseservice.domain.Product();
        obj.setCompetition(null);
        obj.setProductType(null);
        return obj;
    }
    
    public Product ProductDataOnDemand.getSpecificProduct(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Product obj = data.get(index);
        return Product.findProduct(obj.getId());
    }
    
    public Product ProductDataOnDemand.getRandomProduct() {
        init();
        Product obj = data.get(rnd.nextInt(data.size()));
        return Product.findProduct(obj.getId());
    }
    
    public boolean ProductDataOnDemand.modifyProduct(Product obj) {
        return false;
    }
    
    public void ProductDataOnDemand.init() {
        data = org.powertac.server.module.databaseservice.domain.Product.findProductEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Product' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<org.powertac.server.module.databaseservice.domain.Product>();
        for (int i = 0; i < 10; i++) {
            org.powertac.server.module.databaseservice.domain.Product obj = getNewTransientProduct(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
