// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.powertac.server.module.databaseservice.domain;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.powertac.server.module.databaseservice.domain.QuoteLogDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect QuoteLogIntegrationTest_Roo_IntegrationTest {
    
    declare @type: QuoteLogIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: QuoteLogIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: QuoteLogIntegrationTest: @Transactional;
    
    @Autowired
    private QuoteLogDataOnDemand QuoteLogIntegrationTest.dod;
    
    @Test
    public void QuoteLogIntegrationTest.testCountQuoteLogs() {
        org.junit.Assert.assertNotNull("Data on demand for 'QuoteLog' failed to initialize correctly", dod.getRandomQuoteLog());
        long count = org.powertac.server.module.databaseservice.domain.QuoteLog.countQuoteLogs();
        org.junit.Assert.assertTrue("Counter for 'QuoteLog' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void QuoteLogIntegrationTest.testFindQuoteLog() {
        org.powertac.server.module.databaseservice.domain.QuoteLog obj = dod.getRandomQuoteLog();
        org.junit.Assert.assertNotNull("Data on demand for 'QuoteLog' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'QuoteLog' failed to provide an identifier", id);
        obj = org.powertac.server.module.databaseservice.domain.QuoteLog.findQuoteLog(id);
        org.junit.Assert.assertNotNull("Find method for 'QuoteLog' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'QuoteLog' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void QuoteLogIntegrationTest.testFindAllQuoteLogs() {
        org.junit.Assert.assertNotNull("Data on demand for 'QuoteLog' failed to initialize correctly", dod.getRandomQuoteLog());
        long count = org.powertac.server.module.databaseservice.domain.QuoteLog.countQuoteLogs();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'QuoteLog', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<org.powertac.server.module.databaseservice.domain.QuoteLog> result = org.powertac.server.module.databaseservice.domain.QuoteLog.findAllQuoteLogs();
        org.junit.Assert.assertNotNull("Find all method for 'QuoteLog' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'QuoteLog' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void QuoteLogIntegrationTest.testFindQuoteLogEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'QuoteLog' failed to initialize correctly", dod.getRandomQuoteLog());
        long count = org.powertac.server.module.databaseservice.domain.QuoteLog.countQuoteLogs();
        if (count > 20) count = 20;
        java.util.List<org.powertac.server.module.databaseservice.domain.QuoteLog> result = org.powertac.server.module.databaseservice.domain.QuoteLog.findQuoteLogEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'QuoteLog' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'QuoteLog' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void QuoteLogIntegrationTest.testFlush() {
        org.powertac.server.module.databaseservice.domain.QuoteLog obj = dod.getRandomQuoteLog();
        org.junit.Assert.assertNotNull("Data on demand for 'QuoteLog' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'QuoteLog' failed to provide an identifier", id);
        obj = org.powertac.server.module.databaseservice.domain.QuoteLog.findQuoteLog(id);
        org.junit.Assert.assertNotNull("Find method for 'QuoteLog' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyQuoteLog(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'QuoteLog' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void QuoteLogIntegrationTest.testMerge() {
        org.powertac.server.module.databaseservice.domain.QuoteLog obj = dod.getRandomQuoteLog();
        org.junit.Assert.assertNotNull("Data on demand for 'QuoteLog' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'QuoteLog' failed to provide an identifier", id);
        obj = org.powertac.server.module.databaseservice.domain.QuoteLog.findQuoteLog(id);
        boolean modified =  dod.modifyQuoteLog(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        org.powertac.server.module.databaseservice.domain.QuoteLog merged = (org.powertac.server.module.databaseservice.domain.QuoteLog) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'QuoteLog' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void QuoteLogIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'QuoteLog' failed to initialize correctly", dod.getRandomQuoteLog());
        org.powertac.server.module.databaseservice.domain.QuoteLog obj = dod.getNewTransientQuoteLog(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'QuoteLog' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'QuoteLog' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'QuoteLog' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void QuoteLogIntegrationTest.testRemove() {
        org.powertac.server.module.databaseservice.domain.QuoteLog obj = dod.getRandomQuoteLog();
        org.junit.Assert.assertNotNull("Data on demand for 'QuoteLog' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'QuoteLog' failed to provide an identifier", id);
        obj = org.powertac.server.module.databaseservice.domain.QuoteLog.findQuoteLog(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'QuoteLog' with identifier '" + id + "'", org.powertac.server.module.databaseservice.domain.QuoteLog.findQuoteLog(id));
    }
    
}
