// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.powertac.server.module.databaseservice.domain;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.powertac.server.module.databaseservice.domain.StockRecordDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect StockRecordIntegrationTest_Roo_IntegrationTest {
    
    declare @type: StockRecordIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: StockRecordIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: StockRecordIntegrationTest: @Transactional;
    
    @Autowired
    private StockRecordDataOnDemand StockRecordIntegrationTest.dod;
    
    @Test
    public void StockRecordIntegrationTest.testCountStockRecords() {
        org.junit.Assert.assertNotNull("Data on demand for 'StockRecord' failed to initialize correctly", dod.getRandomStockRecord());
        long count = org.powertac.server.module.databaseservice.domain.StockRecord.countStockRecords();
        org.junit.Assert.assertTrue("Counter for 'StockRecord' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void StockRecordIntegrationTest.testFindStockRecord() {
        org.powertac.server.module.databaseservice.domain.StockRecord obj = dod.getRandomStockRecord();
        org.junit.Assert.assertNotNull("Data on demand for 'StockRecord' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'StockRecord' failed to provide an identifier", id);
        obj = org.powertac.server.module.databaseservice.domain.StockRecord.findStockRecord(id);
        org.junit.Assert.assertNotNull("Find method for 'StockRecord' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'StockRecord' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void StockRecordIntegrationTest.testFindAllStockRecords() {
        org.junit.Assert.assertNotNull("Data on demand for 'StockRecord' failed to initialize correctly", dod.getRandomStockRecord());
        long count = org.powertac.server.module.databaseservice.domain.StockRecord.countStockRecords();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'StockRecord', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<org.powertac.server.module.databaseservice.domain.StockRecord> result = org.powertac.server.module.databaseservice.domain.StockRecord.findAllStockRecords();
        org.junit.Assert.assertNotNull("Find all method for 'StockRecord' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'StockRecord' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void StockRecordIntegrationTest.testFindStockRecordEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'StockRecord' failed to initialize correctly", dod.getRandomStockRecord());
        long count = org.powertac.server.module.databaseservice.domain.StockRecord.countStockRecords();
        if (count > 20) count = 20;
        java.util.List<org.powertac.server.module.databaseservice.domain.StockRecord> result = org.powertac.server.module.databaseservice.domain.StockRecord.findStockRecordEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'StockRecord' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'StockRecord' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void StockRecordIntegrationTest.testFlush() {
        org.powertac.server.module.databaseservice.domain.StockRecord obj = dod.getRandomStockRecord();
        org.junit.Assert.assertNotNull("Data on demand for 'StockRecord' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'StockRecord' failed to provide an identifier", id);
        obj = org.powertac.server.module.databaseservice.domain.StockRecord.findStockRecord(id);
        org.junit.Assert.assertNotNull("Find method for 'StockRecord' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyStockRecord(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'StockRecord' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void StockRecordIntegrationTest.testMerge() {
        org.powertac.server.module.databaseservice.domain.StockRecord obj = dod.getRandomStockRecord();
        org.junit.Assert.assertNotNull("Data on demand for 'StockRecord' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'StockRecord' failed to provide an identifier", id);
        obj = org.powertac.server.module.databaseservice.domain.StockRecord.findStockRecord(id);
        boolean modified =  dod.modifyStockRecord(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        org.powertac.server.module.databaseservice.domain.StockRecord merged = (org.powertac.server.module.databaseservice.domain.StockRecord) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'StockRecord' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void StockRecordIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'StockRecord' failed to initialize correctly", dod.getRandomStockRecord());
        org.powertac.server.module.databaseservice.domain.StockRecord obj = dod.getNewTransientStockRecord(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'StockRecord' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'StockRecord' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'StockRecord' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void StockRecordIntegrationTest.testRemove() {
        org.powertac.server.module.databaseservice.domain.StockRecord obj = dod.getRandomStockRecord();
        org.junit.Assert.assertNotNull("Data on demand for 'StockRecord' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'StockRecord' failed to provide an identifier", id);
        obj = org.powertac.server.module.databaseservice.domain.StockRecord.findStockRecord(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'StockRecord' with identifier '" + id + "'", org.powertac.server.module.databaseservice.domain.StockRecord.findStockRecord(id));
    }
    
}
