// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.powertac.server.module.databaseservice.domain;

import java.util.List;
import java.util.Random;
import org.powertac.server.module.databaseservice.domain.Tariff;
import org.springframework.stereotype.Component;

privileged aspect TariffDataOnDemand_Roo_DataOnDemand {
    
    declare @type: TariffDataOnDemand: @Component;
    
    private Random TariffDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<Tariff> TariffDataOnDemand.data;
    
    public Tariff TariffDataOnDemand.getNewTransientTariff(int index) {
        org.powertac.server.module.databaseservice.domain.Tariff obj = new org.powertac.server.module.databaseservice.domain.Tariff();
        return obj;
    }
    
    public Tariff TariffDataOnDemand.getSpecificTariff(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Tariff obj = data.get(index);
        return Tariff.findTariff(obj.getId());
    }
    
    public Tariff TariffDataOnDemand.getRandomTariff() {
        init();
        Tariff obj = data.get(rnd.nextInt(data.size()));
        return Tariff.findTariff(obj.getId());
    }
    
    public boolean TariffDataOnDemand.modifyTariff(Tariff obj) {
        return false;
    }
    
    public void TariffDataOnDemand.init() {
        data = org.powertac.server.module.databaseservice.domain.Tariff.findTariffEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Tariff' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<org.powertac.server.module.databaseservice.domain.Tariff>();
        for (int i = 0; i < 10; i++) {
            org.powertac.server.module.databaseservice.domain.Tariff obj = getNewTransientTariff(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
