// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.powertac.server.module.databaseservice.domain;

import java.util.List;
import java.util.Random;
import org.powertac.server.module.databaseservice.domain.Timeslot;
import org.springframework.stereotype.Component;

privileged aspect TimeslotDataOnDemand_Roo_DataOnDemand {
    
    declare @type: TimeslotDataOnDemand: @Component;
    
    private Random TimeslotDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<Timeslot> TimeslotDataOnDemand.data;
    
    public Timeslot TimeslotDataOnDemand.getNewTransientTimeslot(int index) {
        org.powertac.server.module.databaseservice.domain.Timeslot obj = new org.powertac.server.module.databaseservice.domain.Timeslot();
        return obj;
    }
    
    public Timeslot TimeslotDataOnDemand.getSpecificTimeslot(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Timeslot obj = data.get(index);
        return Timeslot.findTimeslot(obj.getId());
    }
    
    public Timeslot TimeslotDataOnDemand.getRandomTimeslot() {
        init();
        Timeslot obj = data.get(rnd.nextInt(data.size()));
        return Timeslot.findTimeslot(obj.getId());
    }
    
    public boolean TimeslotDataOnDemand.modifyTimeslot(Timeslot obj) {
        return false;
    }
    
    public void TimeslotDataOnDemand.init() {
        data = org.powertac.server.module.databaseservice.domain.Timeslot.findTimeslotEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Timeslot' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<org.powertac.server.module.databaseservice.domain.Timeslot>();
        for (int i = 0; i < 10; i++) {
            org.powertac.server.module.databaseservice.domain.Timeslot obj = getNewTransientTimeslot(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
