// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.powertac.server.module.databaseservice.domain;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.powertac.server.module.databaseservice.domain.TimeslotDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect TimeslotIntegrationTest_Roo_IntegrationTest {
    
    declare @type: TimeslotIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: TimeslotIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: TimeslotIntegrationTest: @Transactional;
    
    @Autowired
    private TimeslotDataOnDemand TimeslotIntegrationTest.dod;
    
    @Test
    public void TimeslotIntegrationTest.testCountTimeslots() {
        org.junit.Assert.assertNotNull("Data on demand for 'Timeslot' failed to initialize correctly", dod.getRandomTimeslot());
        long count = org.powertac.server.module.databaseservice.domain.Timeslot.countTimeslots();
        org.junit.Assert.assertTrue("Counter for 'Timeslot' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void TimeslotIntegrationTest.testFindTimeslot() {
        org.powertac.server.module.databaseservice.domain.Timeslot obj = dod.getRandomTimeslot();
        org.junit.Assert.assertNotNull("Data on demand for 'Timeslot' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Timeslot' failed to provide an identifier", id);
        obj = org.powertac.server.module.databaseservice.domain.Timeslot.findTimeslot(id);
        org.junit.Assert.assertNotNull("Find method for 'Timeslot' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Timeslot' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void TimeslotIntegrationTest.testFindAllTimeslots() {
        org.junit.Assert.assertNotNull("Data on demand for 'Timeslot' failed to initialize correctly", dod.getRandomTimeslot());
        long count = org.powertac.server.module.databaseservice.domain.Timeslot.countTimeslots();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Timeslot', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<org.powertac.server.module.databaseservice.domain.Timeslot> result = org.powertac.server.module.databaseservice.domain.Timeslot.findAllTimeslots();
        org.junit.Assert.assertNotNull("Find all method for 'Timeslot' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Timeslot' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void TimeslotIntegrationTest.testFindTimeslotEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Timeslot' failed to initialize correctly", dod.getRandomTimeslot());
        long count = org.powertac.server.module.databaseservice.domain.Timeslot.countTimeslots();
        if (count > 20) count = 20;
        java.util.List<org.powertac.server.module.databaseservice.domain.Timeslot> result = org.powertac.server.module.databaseservice.domain.Timeslot.findTimeslotEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Timeslot' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Timeslot' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void TimeslotIntegrationTest.testFlush() {
        org.powertac.server.module.databaseservice.domain.Timeslot obj = dod.getRandomTimeslot();
        org.junit.Assert.assertNotNull("Data on demand for 'Timeslot' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Timeslot' failed to provide an identifier", id);
        obj = org.powertac.server.module.databaseservice.domain.Timeslot.findTimeslot(id);
        org.junit.Assert.assertNotNull("Find method for 'Timeslot' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyTimeslot(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Timeslot' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TimeslotIntegrationTest.testMerge() {
        org.powertac.server.module.databaseservice.domain.Timeslot obj = dod.getRandomTimeslot();
        org.junit.Assert.assertNotNull("Data on demand for 'Timeslot' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Timeslot' failed to provide an identifier", id);
        obj = org.powertac.server.module.databaseservice.domain.Timeslot.findTimeslot(id);
        boolean modified =  dod.modifyTimeslot(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        org.powertac.server.module.databaseservice.domain.Timeslot merged = (org.powertac.server.module.databaseservice.domain.Timeslot) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Timeslot' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TimeslotIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Timeslot' failed to initialize correctly", dod.getRandomTimeslot());
        org.powertac.server.module.databaseservice.domain.Timeslot obj = dod.getNewTransientTimeslot(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Timeslot' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Timeslot' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Timeslot' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void TimeslotIntegrationTest.testRemove() {
        org.powertac.server.module.databaseservice.domain.Timeslot obj = dod.getRandomTimeslot();
        org.junit.Assert.assertNotNull("Data on demand for 'Timeslot' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Timeslot' failed to provide an identifier", id);
        obj = org.powertac.server.module.databaseservice.domain.Timeslot.findTimeslot(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Timeslot' with identifier '" + id + "'", org.powertac.server.module.databaseservice.domain.Timeslot.findTimeslot(id));
    }
    
}
