// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.powertac.server.module.databaseservice.domain;

import java.util.List;
import java.util.Random;
import org.powertac.server.module.databaseservice.domain.TradeLog;
import org.springframework.stereotype.Component;

privileged aspect TradeLogDataOnDemand_Roo_DataOnDemand {
    
    declare @type: TradeLogDataOnDemand: @Component;
    
    private Random TradeLogDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<TradeLog> TradeLogDataOnDemand.data;
    
    public TradeLog TradeLogDataOnDemand.getNewTransientTradeLog(int index) {
        org.powertac.server.module.databaseservice.domain.TradeLog obj = new org.powertac.server.module.databaseservice.domain.TradeLog();
        return obj;
    }
    
    public TradeLog TradeLogDataOnDemand.getSpecificTradeLog(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        TradeLog obj = data.get(index);
        return TradeLog.findTradeLog(obj.getId());
    }
    
    public TradeLog TradeLogDataOnDemand.getRandomTradeLog() {
        init();
        TradeLog obj = data.get(rnd.nextInt(data.size()));
        return TradeLog.findTradeLog(obj.getId());
    }
    
    public boolean TradeLogDataOnDemand.modifyTradeLog(TradeLog obj) {
        return false;
    }
    
    public void TradeLogDataOnDemand.init() {
        data = org.powertac.server.module.databaseservice.domain.TradeLog.findTradeLogEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'TradeLog' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<org.powertac.server.module.databaseservice.domain.TradeLog>();
        for (int i = 0; i < 10; i++) {
            org.powertac.server.module.databaseservice.domain.TradeLog obj = getNewTransientTradeLog(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
