// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.powertac.server.module.databaseservice.domain;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.powertac.server.module.databaseservice.domain.TradeLogDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect TradeLogIntegrationTest_Roo_IntegrationTest {
    
    declare @type: TradeLogIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: TradeLogIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: TradeLogIntegrationTest: @Transactional;
    
    @Autowired
    private TradeLogDataOnDemand TradeLogIntegrationTest.dod;
    
    @Test
    public void TradeLogIntegrationTest.testCountTradeLogs() {
        org.junit.Assert.assertNotNull("Data on demand for 'TradeLog' failed to initialize correctly", dod.getRandomTradeLog());
        long count = org.powertac.server.module.databaseservice.domain.TradeLog.countTradeLogs();
        org.junit.Assert.assertTrue("Counter for 'TradeLog' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void TradeLogIntegrationTest.testFindTradeLog() {
        org.powertac.server.module.databaseservice.domain.TradeLog obj = dod.getRandomTradeLog();
        org.junit.Assert.assertNotNull("Data on demand for 'TradeLog' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'TradeLog' failed to provide an identifier", id);
        obj = org.powertac.server.module.databaseservice.domain.TradeLog.findTradeLog(id);
        org.junit.Assert.assertNotNull("Find method for 'TradeLog' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'TradeLog' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void TradeLogIntegrationTest.testFindAllTradeLogs() {
        org.junit.Assert.assertNotNull("Data on demand for 'TradeLog' failed to initialize correctly", dod.getRandomTradeLog());
        long count = org.powertac.server.module.databaseservice.domain.TradeLog.countTradeLogs();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'TradeLog', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<org.powertac.server.module.databaseservice.domain.TradeLog> result = org.powertac.server.module.databaseservice.domain.TradeLog.findAllTradeLogs();
        org.junit.Assert.assertNotNull("Find all method for 'TradeLog' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'TradeLog' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void TradeLogIntegrationTest.testFindTradeLogEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'TradeLog' failed to initialize correctly", dod.getRandomTradeLog());
        long count = org.powertac.server.module.databaseservice.domain.TradeLog.countTradeLogs();
        if (count > 20) count = 20;
        java.util.List<org.powertac.server.module.databaseservice.domain.TradeLog> result = org.powertac.server.module.databaseservice.domain.TradeLog.findTradeLogEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'TradeLog' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'TradeLog' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void TradeLogIntegrationTest.testFlush() {
        org.powertac.server.module.databaseservice.domain.TradeLog obj = dod.getRandomTradeLog();
        org.junit.Assert.assertNotNull("Data on demand for 'TradeLog' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'TradeLog' failed to provide an identifier", id);
        obj = org.powertac.server.module.databaseservice.domain.TradeLog.findTradeLog(id);
        org.junit.Assert.assertNotNull("Find method for 'TradeLog' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyTradeLog(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'TradeLog' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TradeLogIntegrationTest.testMerge() {
        org.powertac.server.module.databaseservice.domain.TradeLog obj = dod.getRandomTradeLog();
        org.junit.Assert.assertNotNull("Data on demand for 'TradeLog' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'TradeLog' failed to provide an identifier", id);
        obj = org.powertac.server.module.databaseservice.domain.TradeLog.findTradeLog(id);
        boolean modified =  dod.modifyTradeLog(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        org.powertac.server.module.databaseservice.domain.TradeLog merged = (org.powertac.server.module.databaseservice.domain.TradeLog) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'TradeLog' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TradeLogIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'TradeLog' failed to initialize correctly", dod.getRandomTradeLog());
        org.powertac.server.module.databaseservice.domain.TradeLog obj = dod.getNewTransientTradeLog(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'TradeLog' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'TradeLog' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'TradeLog' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void TradeLogIntegrationTest.testRemove() {
        org.powertac.server.module.databaseservice.domain.TradeLog obj = dod.getRandomTradeLog();
        org.junit.Assert.assertNotNull("Data on demand for 'TradeLog' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'TradeLog' failed to provide an identifier", id);
        obj = org.powertac.server.module.databaseservice.domain.TradeLog.findTradeLog(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'TradeLog' with identifier '" + id + "'", org.powertac.server.module.databaseservice.domain.TradeLog.findTradeLog(id));
    }
    
}
