// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.powertac.server.module.databaseservice.domain;

import java.util.List;
import java.util.Random;
import org.powertac.server.module.databaseservice.domain.TransactionLog;
import org.springframework.stereotype.Component;

privileged aspect TransactionLogDataOnDemand_Roo_DataOnDemand {
    
    declare @type: TransactionLogDataOnDemand: @Component;
    
    private Random TransactionLogDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<TransactionLog> TransactionLogDataOnDemand.data;
    
    public TransactionLog TransactionLogDataOnDemand.getNewTransientTransactionLog(int index) {
        org.powertac.server.module.databaseservice.domain.TransactionLog obj = new org.powertac.server.module.databaseservice.domain.TransactionLog();
        return obj;
    }
    
    public TransactionLog TransactionLogDataOnDemand.getSpecificTransactionLog(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        TransactionLog obj = data.get(index);
        return TransactionLog.findTransactionLog(obj.getId());
    }
    
    public TransactionLog TransactionLogDataOnDemand.getRandomTransactionLog() {
        init();
        TransactionLog obj = data.get(rnd.nextInt(data.size()));
        return TransactionLog.findTransactionLog(obj.getId());
    }
    
    public boolean TransactionLogDataOnDemand.modifyTransactionLog(TransactionLog obj) {
        return false;
    }
    
    public void TransactionLogDataOnDemand.init() {
        data = org.powertac.server.module.databaseservice.domain.TransactionLog.findTransactionLogEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'TransactionLog' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<org.powertac.server.module.databaseservice.domain.TransactionLog>();
        for (int i = 0; i < 10; i++) {
            org.powertac.server.module.databaseservice.domain.TransactionLog obj = getNewTransientTransactionLog(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
