// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.powertac.server.core.domain;

import java.util.List;
import java.util.Random;
import org.powertac.server.core.domain.Broker;
import org.springframework.stereotype.Component;

privileged aspect BrokerDataOnDemand_Roo_DataOnDemand {
    
    declare @type: BrokerDataOnDemand: @Component;
    
    private Random BrokerDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<Broker> BrokerDataOnDemand.data;
    
    public Broker BrokerDataOnDemand.getNewTransientBroker(int index) {
        org.powertac.server.core.domain.Broker obj = new org.powertac.server.core.domain.Broker();
        obj.setAuthToken("authToken_" + index);
        obj.setUsername("username_" + index);
        return obj;
    }
    
    public Broker BrokerDataOnDemand.getSpecificBroker(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Broker obj = data.get(index);
        return Broker.findBroker(obj.getId());
    }
    
    public Broker BrokerDataOnDemand.getRandomBroker() {
        init();
        Broker obj = data.get(rnd.nextInt(data.size()));
        return Broker.findBroker(obj.getId());
    }
    
    public boolean BrokerDataOnDemand.modifyBroker(Broker obj) {
        return false;
    }
    
    public void BrokerDataOnDemand.init() {
        data = org.powertac.server.core.domain.Broker.findBrokerEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Broker' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<org.powertac.server.core.domain.Broker>();
        for (int i = 0; i < 10; i++) {
            org.powertac.server.core.domain.Broker obj = getNewTransientBroker(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
