// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.powertac.server.core.domain;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.powertac.server.core.domain.CashPositionDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect CashPositionIntegrationTest_Roo_IntegrationTest {
    
    declare @type: CashPositionIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: CashPositionIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: CashPositionIntegrationTest: @Transactional;
    
    @Autowired
    private CashPositionDataOnDemand CashPositionIntegrationTest.dod;
    
    @Test
    public void CashPositionIntegrationTest.testCountCashPositions() {
        org.junit.Assert.assertNotNull("Data on demand for 'CashPosition' failed to initialize correctly", dod.getRandomCashPosition());
        long count = org.powertac.server.core.domain.CashPosition.countCashPositions();
        org.junit.Assert.assertTrue("Counter for 'CashPosition' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void CashPositionIntegrationTest.testFindCashPosition() {
        org.powertac.server.core.domain.CashPosition obj = dod.getRandomCashPosition();
        org.junit.Assert.assertNotNull("Data on demand for 'CashPosition' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'CashPosition' failed to provide an identifier", id);
        obj = org.powertac.server.core.domain.CashPosition.findCashPosition(id);
        org.junit.Assert.assertNotNull("Find method for 'CashPosition' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'CashPosition' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void CashPositionIntegrationTest.testFindAllCashPositions() {
        org.junit.Assert.assertNotNull("Data on demand for 'CashPosition' failed to initialize correctly", dod.getRandomCashPosition());
        long count = org.powertac.server.core.domain.CashPosition.countCashPositions();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'CashPosition', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<org.powertac.server.core.domain.CashPosition> result = org.powertac.server.core.domain.CashPosition.findAllCashPositions();
        org.junit.Assert.assertNotNull("Find all method for 'CashPosition' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'CashPosition' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void CashPositionIntegrationTest.testFindCashPositionEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'CashPosition' failed to initialize correctly", dod.getRandomCashPosition());
        long count = org.powertac.server.core.domain.CashPosition.countCashPositions();
        if (count > 20) count = 20;
        java.util.List<org.powertac.server.core.domain.CashPosition> result = org.powertac.server.core.domain.CashPosition.findCashPositionEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'CashPosition' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'CashPosition' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void CashPositionIntegrationTest.testFlush() {
        org.powertac.server.core.domain.CashPosition obj = dod.getRandomCashPosition();
        org.junit.Assert.assertNotNull("Data on demand for 'CashPosition' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'CashPosition' failed to provide an identifier", id);
        obj = org.powertac.server.core.domain.CashPosition.findCashPosition(id);
        org.junit.Assert.assertNotNull("Find method for 'CashPosition' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyCashPosition(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'CashPosition' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CashPositionIntegrationTest.testMerge() {
        org.powertac.server.core.domain.CashPosition obj = dod.getRandomCashPosition();
        org.junit.Assert.assertNotNull("Data on demand for 'CashPosition' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'CashPosition' failed to provide an identifier", id);
        obj = org.powertac.server.core.domain.CashPosition.findCashPosition(id);
        boolean modified =  dod.modifyCashPosition(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        org.powertac.server.core.domain.CashPosition merged = (org.powertac.server.core.domain.CashPosition) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'CashPosition' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CashPositionIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'CashPosition' failed to initialize correctly", dod.getRandomCashPosition());
        org.powertac.server.core.domain.CashPosition obj = dod.getNewTransientCashPosition(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'CashPosition' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'CashPosition' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'CashPosition' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void CashPositionIntegrationTest.testRemove() {
        org.powertac.server.core.domain.CashPosition obj = dod.getRandomCashPosition();
        org.junit.Assert.assertNotNull("Data on demand for 'CashPosition' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'CashPosition' failed to provide an identifier", id);
        obj = org.powertac.server.core.domain.CashPosition.findCashPosition(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'CashPosition' with identifier '" + id + "'", org.powertac.server.core.domain.CashPosition.findCashPosition(id));
    }
    
}
