/*
 * Copyright 2011 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an
 * "AS IS" BASIS,  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
package org.powertac.common;

import org.apache.log4j.Logger;
import org.joda.time.Instant;
import org.powertac.common.xml.BrokerConverter;

import com.thoughtworks.xstream.annotations.*;

/**
 * Represents interest charges and payments for brokers. Generated by
 * AccountingService once/day.
 * @author John Collins
 */
@XStreamAlias("bank-tx")
public class BankTransaction
{
  static private Logger stateLog = Logger.getLogger("State");
  
  @XStreamAsAttribute
  private long id = IdGenerator.createId();
  
  /** The broker for this transactions */
  @XStreamConverter(BrokerConverter.class)
  private Broker broker;
  
  /** The amount of this transaction */
  @XStreamAsAttribute
  private double amount = 0.0;
  
  /** When this transaction occurred  */
  private Instant postedTime;

  /**
   * Constructs a new BankTransaction instance, giving it a new id.
   */
  public BankTransaction (Broker broker, double amount, Instant time)
  {
    this.broker = broker;
    this.amount = amount;
    this.postedTime = time;
    stateLog.info("BankTransaction:" + this.id + ":new:" + time.getMillis() + ":" + broker.getUsername() +
                  ":" + amount);
  }

  public long getId ()
  {
    return id;
  }

  public Broker getBroker ()
  {
    return broker;
  }

  public double getAmount ()
  {
    return amount;
  }

  public Instant getPostedTime ()
  {
    return postedTime;
  }
}
