/*
 * Copyright 2011 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an
 * "AS IS" BASIS,  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
package org.powertac.common;

import org.joda.time.Instant;
import com.thoughtworks.xstream.annotations.*;

/**
 * Represents interest charges and payments for brokers. Generated by
 * AccountingService once/day.
 * @author John Collins
 */
@XStreamAlias("bank-tx")
public class BankTransaction
{
  private int id;
  
  /** The broker for this transactions */
  @XStreamAsAttribute
  private String brokerId;
  
  /** The amount of this transaction */
  @XStreamAsAttribute
  private double amount = 0.0;
  
  /** When this transaction occurred  */
  private Instant postedTime;

  /**
   * Constructs a new BankTransaction instance, giving it a new id.
   */
  public BankTransaction (String brokerId, double amount, Instant time)
  {
    this.id = makeId();
    this.brokerId = brokerId;
    this.amount = amount;
    this.postedTime = time;
  }

  /**
   * Reconstructs a BankTransaction instance from message or logfile.
   * Do we need this???
   */
  public BankTransaction (int id, String brokerId, double amount, Instant time)
  {
    this.id = id;
    this.brokerId = brokerId;
    this.amount = amount;
    this.postedTime = time;
  }

  public int getId ()
  {
    return id;
  }

  public String getBrokerId ()
  {
    return brokerId;
  }

  public double getAmount ()
  {
    return amount;
  }

  public Instant getPostedTime ()
  {
    return postedTime;
  }
  
  // static ID management
  private static int idValue = 0;
  
  private static synchronized int makeId ()
  {
    return idValue++;
  }
}
