/*
 * Copyright 2009-2011 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an
 * "AS IS" BASIS,  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */

package org.powertac.common;

/**
 * A broker domain instance represents a competition participants, or more
 * precisely the competition participant's agent. Every incoming request
 * from a broker agent is authenticated against the credentials stored in this class.
 * Broker instances are not communicated to other brokers; only usernames are 
 * considered public information and get communicated.
 *
 * @author Carsten Block, David Dauer
 * @version 1.1 , 03/22/2011
 */
public class Broker 
{
  private long id = IdGenerator.createId();

  /** the broker's login or user name     */
  private String username;
  /* Spring Security-related generated fields */
  private String password;
  private boolean enabled;
  private boolean accountExpired;
  private boolean accountLocked;
  private boolean passwordExpired;

  /** If true, the broker is local to the server and does not receive messages  */
  private boolean local = false;
  
  /** If true, broker is a wholesale market participant, but not a "real" broker */
  private boolean wholesale = false;

  //def testProxy = null // redirect incoming messages for testing

  /**
   * Constructor for username only.
   */
  public Broker (String username)
  {
    super();
    this.username = username;
  }
  
  /**
   * Constructor to specify non-standard local/wholesale flags.
   */
  public Broker (String username, boolean local, boolean wholesale)
  {
    super();
    this.username = username;
    this.local = local;
    this.wholesale = wholesale;
  }
  
  /** Broker's current cash position  */
  private CashPosition cashPosn;

  public long getId ()
  {
    return id;
  }
  
  public String getApiKey() 
  {
    return Long.toString(id);
  }

  public CashPosition getCash() 
  {
    if (cashPosn == null) {
      cashPosn = new CashPosition(0.0);
      //cashPosn.save()
    }
    return cashPosn;
  }

  public void setCash(CashPosition thing) 
  {
    cashPosn = thing;
  }

  // Generated by Spring Security

  //Set<Role> getAuthorities() {
  //  BrokerRole.findAllByBroker(this).collect { it.role } as Set
  //}

  public String getUsername ()
  {
    return username;
  }

  public String getPassword ()
  {
    return password;
  }

  public boolean isEnabled ()
  {
    return enabled;
  }

  public boolean isLocal ()
  {
    return local;
  }

  public boolean isWholesale ()
  {
    return wholesale;
  }

  public String toString() 
  {
    return username;
  }

  public String toQueueName() 
  {
    return ("brokers." + this.username + ".outputQueue");
  }

  /**
   * default implementation does nothing.
   * brokers shipping within the server can overwrite this method to receive messages from BrokerProxy
   * @param object the message object received from BrokerProxy
   */
  public void receiveMessage(Object object) 
  {
    //if (!local) {
    //  log.error "receiveMessage() should only be called for local brokers"
    //}
    //testProxy?.receive(object)
  }
}
