// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.powertac.server.module.databaseservice.domain;

import java.io.Serializable;

privileged aspect TradeLog_Roo_Serializable {
    
    declare parents: TradeLog implements Serializable;
    
    private static final long TradeLog.serialVersionUID = 1L;
    
}
