name: Maven Tests

on:
  # run when pushing to master or develop
  push:
    branches: [master, develop]
  # run when opening, synchronizing, or reopening a pull request
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build_and_test:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: maven
      - name: Build and verify with Maven
        run: mvn -B verify --file pom.xml -DargLine="${{env.JVM_ARGS}}"
        env:
          JVM_ARGS: --add-opens java.base/java.util=ALL-UNNAMED
